FROM python:3.6

#ENV LC_ALL="C.UTF-8"

# This python image already includes pip

# -- create the working directory in the container:
RUN mkdir /app
WORKDIR /app

# -- copy the app files in the container's working directory
COPY ./app_cardset.py ./shared.py ./shared_db.py /app/
COPY ./reference_test_data.py ./test_app_cardset.py ./test_utils.py /app/
COPY ./requirements_cardset.txt /app

# -- check what is in the container's working directory
RUN ls -al /app

#RUN which python
#RUN ls -al /usr/local/bin/pyt*
#RUN python --version
#RUN /usr/local/bin/python --version

# -- install the dependencies
RUN pip install -r requirements_cardset.txt

# -- expose the server port
#EXPOSE 8080

# -- Launches the server
ENTRYPOINT ["python","-u","-m","unittest","test_app_cardset.py"]
