FROM ubuntu:18.04

# This image aims at enabling a local Mongo DB for dev and test
# purpose only. It does NOT meet the requirements for a production
# environment.

# -- import the public key used by the package management system
RUN wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add -

# -- Create a list file for MongoDB
RUN echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.2.list

# -- reload local package database
RUN apt-get update

# -- install mongoDB and prevent an upgrade of the version 
RUN apt-get install -y mongodb-org
RUN echo "mongodb-org hold" | dpkg --set-selections

# -- expose the server port
#EXPOSE 27017-27019

# -- Launches the MongoDB service
ENTRYPOINT ["service","mongod","start"]
